"use client";

import { BrainCircuit, ShieldCheck, AlertTriangle, Activity, Search, ChevronDown } from "lucide-react";
import Link from "next/link";

export default function AIRiskInsightsPage() {
  const projects = [
    { id: "PRJ-400259", name: "Ghatampur Thermal Power Plant 3 X 660 MW", risk: "CRITICAL", score: 85, progress: 55.60 },
    { id: "PRJ-702639", name: "Ahmedabad Metro Rail Project Phase-II", risk: "CRITICAL", score: 93, progress: 55.33 },
    { id: "PRJ-607701", name: "Guwahati Refinery Expansion (1.0 to 1.2 MMTPA) along ...", risk: "CRITICAL", score: 91, progress: 44.91 },
  ];

  return (
    <div className="p-8 max-w-6xl mx-auto relative min-h-[calc(100vh-64px)] pb-24">
      
      <div className="mb-8">
        <h1 className="text-3xl font-black text-emerald-600 mb-2">AI Risk Insights</h1>
        <p className="text-sm font-medium text-slate-500">
          Deep dive into predictive risk factors and model explanations to support your field reviews.
        </p>
      </div>

      {/* AI Assist Notice */}
      <div className="bg-blue-50/50 border border-blue-200 rounded-[2rem] p-5 flex gap-4 mb-8">
        <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center text-blue-600 shrink-0">
          <BrainCircuit className="w-5 h-5" />
        </div>
        <div>
          <h4 className="text-[13px] font-bold text-slate-900 mb-1">AI Assist Notice</h4>
          <p className="text-[12px] text-blue-800/80 leading-relaxed">
            These insights are generated by the PRAGYA AI prototype to support human decision-making. <strong>Feature contributions describe the model's prediction; they do not establish causation.</strong> Verify all anomalies with the implementing agency before taking official action.
          </p>
        </div>
      </div>

      {/* Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-10">
        <div className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100 flex flex-col justify-between">
          <div className="flex items-center gap-2 text-slate-500 mb-6">
            <ShieldCheck className="w-4 h-4" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Total Projects Monitored</span>
          </div>
          <div>
            <h3 className="text-3xl font-black text-slate-900">2111</h3>
            <p className="text-[11px] text-slate-400 mt-1">System wide coverage</p>
          </div>
        </div>

        <div className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100 flex flex-col justify-between">
          <div className="flex items-center gap-2 text-red-500 mb-6">
            <AlertTriangle className="w-4 h-4" />
            <span className="text-[10px] font-bold uppercase tracking-widest">High/Critical Risk</span>
          </div>
          <div>
            <h3 className="text-3xl font-black text-red-500">107</h3>
            <p className="text-[11px] text-slate-400 mt-1">Requiring immediate attention</p>
          </div>
        </div>

        <div className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100 flex flex-col justify-between">
          <div className="flex items-center gap-2 text-slate-500 mb-6">
            <Activity className="w-4 h-4" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Last Analysis</span>
          </div>
          <div>
            <h3 className="text-3xl font-black text-slate-900">Today</h3>
            <p className="text-[11px] text-slate-400 mt-1">Based on latest reporting data</p>
          </div>
        </div>
      </div>

      {/* Project Risk Register */}
      <div>
        <h3 className="text-sm font-black text-slate-900 mb-4 tracking-tight">Project Risk Register</h3>
        
        <div className="bg-white rounded-[2rem] shadow-sm border border-slate-100 overflow-hidden">
          <div className="p-4 border-b border-slate-100 flex items-center justify-between gap-4 bg-slate-50/50">
            <div className="relative flex-1 max-w-md">
              <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input 
                type="text" 
                placeholder="Search by Project ID or Name..." 
                className="w-full pl-9 pr-4 py-2 rounded-full border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
            </div>
            <div className="relative">
              <select className="appearance-none bg-white border border-slate-200 text-sm font-medium pl-4 pr-10 py-2 rounded-full focus:outline-none focus:ring-2 focus:ring-emerald-500 cursor-pointer">
                <option>All Risk Levels</option>
                <option>Critical</option>
                <option>High</option>
              </select>
              <ChevronDown className="w-4 h-4 absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
            </div>
          </div>

          <table className="w-full text-left text-sm">
            <thead className="bg-white text-[10px] uppercase font-bold text-slate-400 tracking-widest">
              <tr>
                <th className="px-6 py-4 font-bold">Project ID</th>
                <th className="px-6 py-4 font-bold text-center">Overall Risk</th>
                <th className="px-6 py-4 font-bold text-center">Score</th>
                <th className="px-6 py-4 font-bold">Physical Progress</th>
                <th className="px-6 py-4 font-bold text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {projects.map((p) => (
                <tr key={p.id} className="hover:bg-slate-50 transition-colors">
                  <td className="px-6 py-4">
                    <div className="font-bold text-blue-600 mb-1">{p.id}</div>
                    <div className="text-[11px] text-slate-500 truncate max-w-xs">{p.name}</div>
                  </td>
                  <td className="px-6 py-4 text-center">
                    <span className="inline-block px-3 py-1 bg-red-50 text-[10px] font-black text-red-500 rounded-full uppercase tracking-widest border border-red-100">
                      {p.risk}
                    </span>
                  </td>
                  <td className="px-6 py-4 text-center">
                    <span className="font-black text-slate-900">{p.score}</span><span className="text-slate-400 text-xs font-bold">/100</span>
                  </td>
                  <td className="px-6 py-4">
                    <div className="flex items-center gap-3 w-48">
                      <div className="flex-1 h-2 bg-slate-100 rounded-full overflow-hidden">
                        <div className="h-full bg-blue-500 rounded-full" style={{ width: `${p.progress}%` }}></div>
                      </div>
                      <span className="text-[10px] font-bold text-slate-500 w-8">{p.progress}%</span>
                    </div>
                  </td>
                  <td className="px-6 py-4 text-right">
                    <Link href={`/dashboard/officer/projects/${p.id}`} className="inline-flex items-center gap-1 text-[11px] font-black text-blue-600 hover:text-blue-800 uppercase tracking-widest bg-blue-50 px-3 py-1.5 rounded-full transition-colors">
                      Explain <ChevronDown className="w-3 h-3" />
                    </Link>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>
    </div>
  );
}
