"use client";

import { useState, useEffect } from "react";
import { BrainCircuit, ShieldCheck, AlertTriangle, Activity, Search, ChevronDown } from "lucide-react";
import Link from "next/link";
import { motion } from "framer-motion";

export default function AIRiskInsightsPage() {
  const [projects, setProjects] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [searchQuery, setSearchQuery] = useState("");
  const [riskFilter, setRiskFilter] = useState("All Risk Levels");

  // Fetch real data from the backend
  useEffect(() => {
    const fetchProjects = async () => {
      try {
        const res = await fetch("http://127.0.0.1:8000/api/projects");
        if (res.ok) {
          const data = await res.json();
          setProjects(data);
        } else {
          console.error("Failed to fetch projects");
        }
      } catch (error) {
        console.error("API error:", error);
      } finally {
        setLoading(false);
      }
    };
    fetchProjects();
  }, []);

  // Filter logic
  const filteredProjects = projects.filter((p) => {
    const matchesSearch = p.id.toLowerCase().includes(searchQuery.toLowerCase()) || 
                          p.name.toLowerCase().includes(searchQuery.toLowerCase());
    const matchesRisk = riskFilter === "All Risk Levels" || p.risk_level === riskFilter;
    return matchesSearch && matchesRisk;
  });

  // Derived stats
  const totalMonitored = projects.length;
  const highCritical = projects.filter(p => p.risk_level === "High" || p.risk_level === "Critical").length;

  return (
    <div className="p-8 max-w-6xl mx-auto relative min-h-[calc(100vh-64px)] pb-24">
      
      <motion.div 
        initial={{ opacity: 0, y: 20 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="mb-8"
      >
        <h1 className="text-3xl font-black text-emerald-600 mb-2">AI Risk Insights</h1>
        <p className="text-sm font-medium text-slate-500">
          Deep dive into predictive risk factors and model explanations to support your field reviews.
        </p>
      </motion.div>

      {/* AI Assist Notice */}
      <motion.div 
        initial={{ opacity: 0, scale: 0.95 }}
        animate={{ opacity: 1, scale: 1 }}
        transition={{ duration: 0.5, delay: 0.1 }}
        className="bg-blue-50/50 border border-blue-200 rounded-[2rem] p-5 flex gap-4 mb-8 shadow-sm"
      >
        <div className="w-10 h-10 bg-blue-100 rounded-full flex items-center justify-center text-blue-600 shrink-0 shadow-sm">
          <BrainCircuit className="w-5 h-5" />
        </div>
        <div>
          <h4 className="text-[13px] font-bold text-slate-900 mb-1">AI Assist Notice</h4>
          <p className="text-[12px] text-blue-800/80 leading-relaxed">
            These insights are generated by the PRAGYA AI prototype to support human decision-making. <strong>Feature contributions describe the model's prediction; they do not establish causation.</strong> Verify all anomalies with the implementing agency before taking official action.
          </p>
        </div>
      </motion.div>

      {/* Stat Cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-10">
        {[
          { icon: ShieldCheck, color: "text-slate-500", title: "Total Projects Monitored", value: loading ? "..." : totalMonitored, sub: "System wide coverage" },
          { icon: AlertTriangle, color: "text-red-500", title: "High/Critical Risk", value: loading ? "..." : highCritical, sub: "Requiring immediate attention" },
          { icon: Activity, color: "text-slate-500", title: "Last Analysis", value: "Today", sub: "Based on latest reporting data" }
        ].map((stat, idx) => (
          <motion.div 
            key={idx}
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.5, delay: 0.2 + (idx * 0.1) }}
            className="bg-white p-6 rounded-[2rem] shadow-sm border border-slate-100 flex flex-col justify-between hover:shadow-md transition-shadow"
          >
            <div className={`flex items-center gap-2 ${stat.color} mb-6`}>
              <stat.icon className="w-4 h-4" />
              <span className="text-[10px] font-bold uppercase tracking-widest">{stat.title}</span>
            </div>
            <div>
              <h3 className={`text-3xl font-black ${stat.color === 'text-red-500' ? 'text-red-500' : 'text-slate-900'}`}>{stat.value}</h3>
              <p className="text-[11px] text-slate-400 mt-1">{stat.sub}</p>
            </div>
          </motion.div>
        ))}
      </div>

      {/* Project Risk Register */}
      <motion.div
        initial={{ opacity: 0, y: 30 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.6, delay: 0.4 }}
      >
        <h3 className="text-sm font-black text-slate-900 mb-4 tracking-tight">Project Risk Register</h3>
        
        <div className="bg-white rounded-[2rem] shadow-sm border border-slate-100 overflow-hidden">
          <div className="p-4 border-b border-slate-100 flex items-center justify-between gap-4 bg-slate-50/50">
            <div className="relative flex-1 max-w-md">
              <Search className="w-4 h-4 absolute left-3 top-1/2 -translate-y-1/2 text-slate-400" />
              <input 
                type="text" 
                placeholder="Search by Project ID or Name..." 
                value={searchQuery}
                onChange={(e) => setSearchQuery(e.target.value)}
                className="w-full pl-9 pr-4 py-2 rounded-full border border-slate-200 text-sm focus:outline-none focus:ring-2 focus:ring-emerald-500 transition-shadow"
              />
            </div>
            <div className="relative">
              <select 
                value={riskFilter}
                onChange={(e) => setRiskFilter(e.target.value)}
                className="appearance-none bg-white border border-slate-200 text-sm font-medium pl-4 pr-10 py-2 rounded-full focus:outline-none focus:ring-2 focus:ring-emerald-500 cursor-pointer transition-shadow"
              >
                <option value="All Risk Levels">All Risk Levels</option>
                <option value="Critical">Critical</option>
                <option value="High">High</option>
                <option value="Medium">Medium</option>
                <option value="Low">Low</option>
              </select>
              <ChevronDown className="w-4 h-4 absolute right-3 top-1/2 -translate-y-1/2 text-slate-400 pointer-events-none" />
            </div>
          </div>

          <table className="w-full text-left text-sm">
            <thead className="bg-white text-[10px] uppercase font-bold text-slate-400 tracking-widest">
              <tr>
                <th className="px-6 py-4 font-bold">Project ID</th>
                <th className="px-6 py-4 font-bold text-center">Overall Risk</th>
                <th className="px-6 py-4 font-bold text-center">Score</th>
                <th className="px-6 py-4 font-bold">Physical Progress</th>
                <th className="px-6 py-4 font-bold text-right">Action</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-slate-100">
              {loading ? (
                <tr>
                  <td colSpan={5} className="px-6 py-12 text-center text-slate-400 text-xs italic font-medium">
                    <div className="flex justify-center mb-2">
                      <div className="w-6 h-6 border-2 border-emerald-500 border-t-transparent rounded-full animate-spin"></div>
                    </div>
                    Loading AI predictions...
                  </td>
                </tr>
              ) : filteredProjects.length === 0 ? (
                <tr>
                  <td colSpan={5} className="px-6 py-12 text-center text-slate-400 text-xs italic font-medium">
                    No projects found matching the criteria.
                  </td>
                </tr>
              ) : (
                filteredProjects.map((p) => (
                  <motion.tr 
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    key={p.id} 
                    className="hover:bg-slate-50 transition-colors group"
                  >
                    <td className="px-6 py-4">
                      <div className="font-bold text-blue-600 mb-1">{p.id}</div>
                      <div className="text-[11px] text-slate-500 truncate max-w-xs">{p.name}</div>
                    </td>
                    <td className="px-6 py-4 text-center">
                      <span className={`inline-block px-3 py-1 text-[10px] font-black rounded-full uppercase tracking-widest border ${
                        p.risk_level === 'Critical' ? 'bg-red-50 text-red-500 border-red-100' :
                        p.risk_level === 'High' ? 'bg-orange-50 text-orange-500 border-orange-100' :
                        p.risk_level === 'Medium' ? 'bg-yellow-50 text-yellow-600 border-yellow-100' :
                        'bg-emerald-50 text-emerald-500 border-emerald-100'
                      }`}>
                        {p.risk_level}
                      </span>
                    </td>
                    <td className="px-6 py-4 text-center">
                      <span className="font-black text-slate-900">{Math.round(p.risk_score)}</span><span className="text-slate-400 text-xs font-bold">/100</span>
                    </td>
                    <td className="px-6 py-4">
                      <div className="flex items-center gap-3 w-48">
                        <div className="flex-1 h-2 bg-slate-100 rounded-full overflow-hidden">
                          <motion.div 
                            initial={{ width: 0 }}
                            animate={{ width: `${p.physical_progress_pct}%` }}
                            transition={{ duration: 1, ease: "easeOut" }}
                            className="h-full bg-blue-500 rounded-full" 
                          />
                        </div>
                        <span className="text-[10px] font-bold text-slate-500 w-8">{p.physical_progress_pct}%</span>
                      </div>
                    </td>
                    <td className="px-6 py-4 text-right">
                      <Link href={`/dashboard/officer/projects/${p.id}`} className="inline-flex items-center gap-1 text-[11px] font-black text-blue-600 hover:text-blue-800 uppercase tracking-widest bg-blue-50 px-3 py-1.5 rounded-full transition-colors group-hover:bg-blue-100">
                        Explain <ChevronDown className="w-3 h-3 group-hover:rotate-180 transition-transform" />
                      </Link>
                    </td>
                  </motion.tr>
                ))
              )}
            </tbody>
          </table>
        </div>
      </motion.div>
    </div>
  );
}
