"use client";

import { 
  BrainCircuit, 
  Search,
  ChevronDown,
  ShieldCheck,
  AlertTriangle,
  Activity
} from "lucide-react";

export default function OfficerInsights() {
  return (
    <div className="max-w-7xl mx-auto space-y-8">
      <div>
        <h1 className="text-3xl font-extrabold text-emerald-600 dark:text-emerald-500 tracking-tight">AI Risk Insights</h1>
        <p className="text-slate-500 dark:text-slate-400 font-medium mt-1">
          Deep dive into predictive risk factors and model explanations to support your field reviews.
        </p>
      </div>

      <div className="bg-blue-50 dark:bg-blue-900/10 border border-blue-200 dark:border-blue-800 rounded-2xl p-4 flex items-start">
        <div className="bg-blue-100 dark:bg-blue-900/40 p-2 rounded-xl shrink-0 mr-4">
          <BrainCircuit className="w-5 h-5 text-blue-600 dark:text-blue-500" />
        </div>
        <div>
          <h4 className="font-bold text-blue-900 dark:text-blue-400 text-sm mb-1">AI Assist Notice</h4>
          <p className="text-sm text-blue-800 dark:text-blue-300">
            These insights are generated by the PRAGYA AI prototype to support human decision-making. <strong className="font-bold">Feature contributions describe the model's prediction; they do not establish causation.</strong> Verify all anomalies with the implementing agency before taking official action.
          </p>
        </div>
      </div>

      <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between">
          <div className="flex items-center text-slate-500 mb-2">
            <ShieldCheck className="w-4 h-4 mr-2" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Total Projects Monitored</span>
          </div>
          <div className="mt-2">
            <div className="text-3xl font-black text-slate-900 dark:text-white leading-none">2111</div>
            <div className="text-xs text-slate-400 mt-2">System wide coverage</div>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between">
          <div className="flex items-center text-slate-500 mb-2">
            <AlertTriangle className="w-4 h-4 mr-2" />
            <span className="text-[10px] font-bold uppercase tracking-widest">High/Critical Risk</span>
          </div>
          <div className="mt-2">
            <div className="text-3xl font-black text-red-600 dark:text-red-500 leading-none">107</div>
            <div className="text-xs text-slate-400 mt-2">Requiring immediate attention</div>
          </div>
        </div>

        <div className="bg-white dark:bg-slate-900 p-6 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm flex flex-col justify-between">
          <div className="flex items-center text-slate-500 mb-2">
            <Activity className="w-4 h-4 mr-2" />
            <span className="text-[10px] font-bold uppercase tracking-widest">Last Analysis</span>
          </div>
          <div className="mt-2">
            <div className="text-3xl font-black text-slate-900 dark:text-white leading-none">Today</div>
            <div className="text-xs text-slate-400 mt-2">Based on latest reporting data</div>
          </div>
        </div>
      </div>

      <div className="space-y-4">
        <h3 className="text-lg font-bold text-slate-900 dark:text-white">Project Risk Register</h3>
        <div className="bg-white dark:bg-slate-900 rounded-2xl border border-slate-200 dark:border-slate-800 shadow-sm overflow-hidden">
          <div className="p-4 border-b border-slate-100 dark:border-slate-800 flex justify-between items-center bg-slate-50 dark:bg-slate-800/50">
            <div className="relative w-96">
              <div className="absolute inset-y-0 left-0 pl-3 flex items-center pointer-events-none">
                <Search className="h-4 w-4 text-slate-400" />
              </div>
              <input 
                type="text" 
                placeholder="Search by Project ID or Name..."
                className="block w-full pl-10 pr-3 py-2 border border-slate-200 dark:border-slate-700 rounded-lg bg-white dark:bg-slate-900 text-sm placeholder-slate-400 focus:outline-none focus:ring-2 focus:ring-emerald-500"
              />
            </div>
            <div>
              <button className="flex items-center px-4 py-2 border border-slate-200 dark:border-slate-700 rounded-lg bg-white dark:bg-slate-900 text-sm font-semibold text-slate-700 dark:text-slate-300">
                All Risk Levels
                <ChevronDown className="w-4 h-4 ml-2 text-slate-400" />
              </button>
            </div>
          </div>

          <div className="overflow-x-auto">
            <table className="w-full text-left border-collapse">
              <thead>
                <tr className="border-b border-slate-100 dark:border-slate-800">
                  <th className="p-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest">Project ID</th>
                  <th className="p-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest text-center">Overall Risk</th>
                  <th className="p-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest text-center">Score</th>
                  <th className="p-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest">Physical Progress</th>
                  <th className="p-4 text-[10px] font-bold text-slate-500 uppercase tracking-widest text-right">Action</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-slate-100 dark:divide-slate-800">
                
                <tr className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition">
                  <td className="p-4">
                    <div className="font-bold text-blue-600 dark:text-blue-500 text-sm">PRJ-400259</div>
                    <div className="text-[11px] text-slate-400 truncate max-w-[300px]">Ghatampur Thermal Power Plant 3 X 660 MW</div>
                  </td>
                  <td className="p-4 text-center">
                    <span className="bg-red-50 text-red-600 dark:bg-red-900/30 dark:text-red-400 border border-red-100 dark:border-red-900/50 px-2.5 py-1 rounded text-[9px] font-bold uppercase tracking-wider">
                      CRITICAL
                    </span>
                  </td>
                  <td className="p-4 text-center">
                    <div className="font-bold text-slate-900 dark:text-white text-sm">85/100</div>
                  </td>
                  <td className="p-4">
                    <div className="w-40">
                      <div className="h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                        <div className="h-full bg-blue-500" style={{ width: '55.68%' }}></div>
                      </div>
                      <div className="text-[9px] font-bold text-slate-500 mt-1">55.68%</div>
                    </div>
                  </td>
                  <td className="p-4 text-right">
                    <button className="inline-flex items-center px-3 py-1.5 text-blue-600 dark:text-blue-500 text-[10px] font-bold uppercase hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded transition-colors">
                      Explain <ChevronDown className="w-3 h-3 ml-1" />
                    </button>
                  </td>
                </tr>

                <tr className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition">
                  <td className="p-4">
                    <div className="font-bold text-blue-600 dark:text-blue-500 text-sm">PRJ-702639</div>
                    <div className="text-[11px] text-slate-400 truncate max-w-[300px]">Ahmedabad Metro Rail Project (Phase-1)</div>
                  </td>
                  <td className="p-4 text-center">
                    <span className="bg-red-50 text-red-600 dark:bg-red-900/30 dark:text-red-400 border border-red-100 dark:border-red-900/50 px-2.5 py-1 rounded text-[9px] font-bold uppercase tracking-wider">
                      CRITICAL
                    </span>
                  </td>
                  <td className="p-4 text-center">
                    <div className="font-bold text-slate-900 dark:text-white text-sm">93/100</div>
                  </td>
                  <td className="p-4">
                    <div className="w-40">
                      <div className="h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                        <div className="h-full bg-blue-500" style={{ width: '59.99%' }}></div>
                      </div>
                      <div className="text-[9px] font-bold text-slate-500 mt-1">59.99%</div>
                    </div>
                  </td>
                  <td className="p-4 text-right">
                    <button className="inline-flex items-center px-3 py-1.5 text-blue-600 dark:text-blue-500 text-[10px] font-bold uppercase hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded transition-colors">
                      Explain <ChevronDown className="w-3 h-3 ml-1" />
                    </button>
                  </td>
                </tr>

                <tr className="hover:bg-slate-50 dark:hover:bg-slate-800/50 transition">
                  <td className="p-4">
                    <div className="font-bold text-blue-600 dark:text-blue-500 text-sm">PRJ-607701</div>
                    <div className="text-[11px] text-slate-400 truncate max-w-[300px]">Guwahati Refinery Expansion (1.0 to 1.2 MMTPA) along...</div>
                  </td>
                  <td className="p-4 text-center">
                    <span className="bg-red-50 text-red-600 dark:bg-red-900/30 dark:text-red-400 border border-red-100 dark:border-red-900/50 px-2.5 py-1 rounded text-[9px] font-bold uppercase tracking-wider">
                      CRITICAL
                    </span>
                  </td>
                  <td className="p-4 text-center">
                    <div className="font-bold text-slate-900 dark:text-white text-sm">91/100</div>
                  </td>
                  <td className="p-4">
                    <div className="w-40">
                      <div className="h-1.5 bg-slate-100 dark:bg-slate-800 rounded-full overflow-hidden">
                        <div className="h-full bg-blue-500" style={{ width: '94.9%' }}></div>
                      </div>
                      <div className="text-[9px] font-bold text-slate-500 mt-1">94.9%</div>
                    </div>
                  </td>
                  <td className="p-4 text-right">
                    <button className="inline-flex items-center px-3 py-1.5 text-blue-600 dark:text-blue-500 text-[10px] font-bold uppercase hover:bg-blue-50 dark:hover:bg-blue-900/20 rounded transition-colors">
                      Explain <ChevronDown className="w-3 h-3 ml-1" />
                    </button>
                  </td>
                </tr>

              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
  );
}
