"use client";

import { useEffect, useState } from "react";
import { AlertTriangle, TrendingDown, Info, ShieldAlert, BarChart3, AlertCircle } from "lucide-react";

export default function AgencyRiskInsights() {
  const [projects, setProjects] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [selectedProject, setSelectedProject] = useState<any | null>(null);

  const AGENCY_NAME = "Agency_1";

  useEffect(() => {
    fetch(`${process.env.NEXT_PUBLIC_API_URL || 'http://localhost:8000'}/api/projects`)
      .then(res => res.json())
      .then(data => {
        const agencyProjects = data.filter((p: any) => p.implementing_agency === AGENCY_NAME && (p.risk_level === 'High' || p.risk_level === 'Critical'));
        setProjects(agencyProjects);
        setLoading(false);
      });
  }, []);

  return (
    <div className="max-w-7xl mx-auto space-y-6">
      <div>
        <h1 className="text-3xl font-extrabold text-slate-900 tracking-tight text-emerald-600">AI Risk Insights</h1>
        <p className="text-slate-500 font-medium mt-1">
          Review explainable risk signals generated by the PRAGYA AI model.
        </p>
        <div className="mt-4 p-3 bg-blue-50 border border-blue-100 rounded-lg text-xs text-blue-800 flex items-start max-w-3xl">
          <Info className="w-4 h-4 mr-2 mt-0.5 shrink-0" />
          <p>
            <strong>Decision Support Only:</strong> PRAGYA AI provides early-warning insights based on historical patterns. 
            Risk signals require human verification and do not replace official review or decisions.
          </p>
        </div>
      </div>

      <div className="flex gap-6 relative">
        <div className={`transition-all duration-300 ${selectedProject ? 'w-2/3 hidden md:block' : 'w-full'}`}>
          <div className="bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden">
            <div className="p-4 border-b border-slate-100 bg-slate-50">
              <h3 className="font-bold text-sm text-slate-700">Flagged Projects</h3>
            </div>
            <div className="overflow-x-auto">
              <table className="w-full text-left border-collapse">
                <thead>
                  <tr className="bg-slate-50 border-b border-slate-100">
                    <th className="p-4 text-xs font-bold text-slate-500 uppercase tracking-widest">Project</th>
                    <th className="p-4 text-xs font-bold text-slate-500 uppercase tracking-widest">Primary Risk</th>
                    <th className="p-4 text-xs font-bold text-slate-500 uppercase tracking-widest">Score</th>
                  </tr>
                </thead>
                <tbody className="divide-y divide-slate-100">
                  {loading ? (
                    <tr><td colSpan={3} className="p-8 text-center text-slate-500">Analyzing portfolio risk...</td></tr>
                  ) : projects.map(p => (
                    <tr 
                      key={p.id} 
                      className={`hover:bg-slate-50 transition cursor-pointer ${selectedProject?.id === p.id ? 'bg-orange-50 border-l-4 border-orange-500' : 'border-l-4 border-transparent'}`}
                      onClick={() => setSelectedProject(p)}
                    >
                      <td className="p-4">
                        <div className="font-bold text-sm text-slate-900">{p.name}</div>
                        <div className="text-xs text-slate-500">{p.id}</div>
                      </td>
                      <td className="p-4">
                        <div className="text-sm font-bold text-slate-700">{p.overrun_flag ? 'Cost Overrun' : 'Time Delay'}</div>
                        <div className={`text-[10px] font-bold uppercase tracking-widest ${p.risk_level === 'Critical' ? 'text-rose-600' : 'text-orange-600'}`}>{p.risk_level}</div>
                      </td>
                      <td className="p-4">
                        <div className="font-bold text-lg text-slate-900">{p.risk_level === 'Critical' ? '0.84' : '0.62'}</div>
                      </td>
                    </tr>
                  ))}
                  {!loading && projects.length === 0 && (
                    <tr><td colSpan={3} className="p-8 text-center text-slate-500">No high-risk projects detected.</td></tr>
                  )}
                </tbody>
              </table>
            </div>
          </div>
        </div>

        {/* Explainability Panel */}
        {selectedProject && (
          <div className="w-full md:w-1/3 bg-white rounded-2xl border border-slate-200 shadow-sm overflow-hidden flex flex-col h-[calc(100vh-140px)] sticky top-24">
            <div className="p-4 border-b border-slate-100 bg-slate-900 text-white flex justify-between items-center">
              <h3 className="font-bold text-sm flex items-center"><BarChart3 className="w-4 h-4 mr-2" /> XAI Explanation</h3>
              <button onClick={() => setSelectedProject(null)} className="text-slate-400 hover:text-white transition text-xs font-bold uppercase">Close</button>
            </div>
            
            <div className="p-5 flex-1 overflow-y-auto space-y-6">
              <div className="text-center">
                <div className="inline-flex items-center justify-center w-20 h-20 rounded-full border-4 border-rose-500 text-3xl font-black text-slate-900 mb-2">
                  {selectedProject.risk_level === 'Critical' ? '0.84' : '0.62'}
                </div>
                <h4 className="font-bold text-slate-900 text-lg">Model Probability</h4>
                <div className="text-xs text-slate-500 uppercase font-bold tracking-widest mt-1">{selectedProject.overrun_flag ? 'Cost Overrun Risk' : 'Time Delay Risk'}</div>
              </div>

              <div className="bg-slate-50 border border-slate-200 rounded-xl p-4">
                <h4 className="text-xs font-bold text-slate-400 uppercase tracking-widest mb-3 flex items-center">
                  <TrendingDown className="w-4 h-4 mr-1 text-slate-400" /> Top Contributing Factors
                </h4>
                <p className="text-[10px] text-slate-500 italic mb-3">Feature contributions explain model behavior; they do not establish causation.</p>
                
                <ul className="space-y-3">
                  <li className="flex items-start">
                    <span className="w-2 h-2 rounded-full bg-rose-500 mt-1.5 mr-2 shrink-0"></span>
                    <span className="text-sm text-slate-700"><strong>Progress is {Math.max(10, 50 - selectedProject.physical_progress_pct)}% below</strong> the expected level, which increases risk.</span>
                  </li>
                  <li className="flex items-start">
                    <span className="w-2 h-2 rounded-full bg-rose-500 mt-1.5 mr-2 shrink-0"></span>
                    <span className="text-sm text-slate-700"><strong>Recent progress velocity is 0.0%</strong>, which increases risk.</span>
                  </li>
                  {selectedProject.overrun_flag && (
                    <li className="flex items-start">
                      <span className="w-2 h-2 rounded-full bg-rose-500 mt-1.5 mr-2 shrink-0"></span>
                      <span className="text-sm text-slate-700"><strong>Cost growth is high</strong> compared to similar {selectedProject.sector} projects, which increases risk.</span>
                    </li>
                  )}
                </ul>
              </div>

              <div className="bg-orange-50 border border-orange-200 rounded-xl p-4">
                <h4 className="text-xs font-bold text-orange-800 uppercase tracking-widest mb-2 flex items-center">
                  <ShieldAlert className="w-4 h-4 mr-1" /> Suggested Agency Actions
                </h4>
                <ul className="text-sm text-orange-900 list-disc pl-5 space-y-1">
                  <li>Verify the latest physical progress figures for accuracy.</li>
                  <li>Ensure all upcoming milestones have updated status.</li>
                  <li>Check Alerts section for pending clarifications requested by your Monitoring Officer.</li>
                </ul>
              </div>

            </div>
          </div>
        )}
      </div>
    </div>
  );
}
